version: "3.7"

services:

    app:
        build: ./image
        image: nodejs:1.0
        container_name: myapp
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./app:/home/node/app
